### ISSUE TITLE
MIDI panic does not work

### ISSUE THREAD

**Issue by Miq1** [Miq1/FredBoard#5]
### Version

alpha4d

### What is the issue?

The mechanism Fred described to cut off all MIDI traffic (panic) by pressing the 4 outer corner pads simultaneously seems not to work at all. I had several situations where hanging notes were not cut off.

**Comment by Frudah** [comment]
This has been dealt with. Mid panic is now implemented with the two octave change buttons rather than the 4 corners. It should work in scales and classic mode. Will add to other modes shortly. Previous issue was I was sending all notes off messages on all channels, but was not clearing the active note buffers. So, the next key that was pushed would hang notes if the notes were ones that had been turned off, but not cleared in the buffers.

tracking has been improved so this should be less, if not a non-existent midi panic problem.
